import { useEffect, useMemo, useRef, useState } from "react";
import type { Session } from "@supabase/supabase-js";
import { Accessibility, ArrowLeft, ArrowRight, Check, Cloud, CloudOff, LogOut, Pause, Play, RotateCcw, Sparkles, Volume2, VolumeX, X } from "lucide-react";
import { authRedirectUrl, supabase, supabaseConfigured } from "@/lib/supabase";

type Answers = {
  experienceType?: string; task?: string; action?: string; skill?: string; result?: string; bullet?: string;
  lesson?: string; addThisWeek?: string; nextAction?: string; createdResume?: string; ease?: string; support?: string;
};
type Journey = { name:string; scene:number; xp:number; completed:string[]; answers:Answers; completionDate:string };
const MODULE_ID="resume-district", STORAGE_KEY="level-up-resume-district-v1";
const DEFAULT:Journey={name:"",scene:0,xp:0,completed:[],answers:{},completionDate:""};
const PORTAL="https://pinalworkforce1-del.github.io/Level_Up_Portal/";
const titles=["Enter Resume District","The District Map","No Experience? Look Again","Transferable Skills Unlocked","Interview Access","Build the Right Path","Recruiter Perspective","The Keyword Forge","Protect Your Brand","Integrity Unlocked","Your Résumé, Built","Interview Gate Unlocked","Level Up Reflection","Resume District","Interview Arena","First Day Challenge","Money Moves"];
const enhancements:Record<number,{label:string;kind:"lens"|"translator"|"anatomy"|"keywords"|"brand"|"integrity"|"builder"|"reflection"}>={
  2:{label:"Explore life experience",kind:"lens"},3:{label:"Build a résumé bullet",kind:"translator"},5:{label:"Explore résumé anatomy",kind:"anatomy"},7:{label:"Enter the Keyword Forge",kind:"keywords"},8:{label:"Check your digital presence",kind:"brand"},9:{label:"Test résumé integrity",kind:"integrity"},10:{label:"Review your résumé plan",kind:"builder"},12:{label:"Complete Resume District reflection",kind:"reflection"}
};
const lens=[
  ["Caregiving","Coordinating schedules, transportation, meals, or appointments demonstrates reliability, planning, communication, and care."],
  ["School projects","Researching, meeting deadlines, presenting, and working with classmates demonstrate organization, teamwork, and communication."],
  ["Sports and clubs","Practicing consistently, supporting teammates, and adapting under pressure demonstrate discipline, teamwork, and resilience."],
  ["Volunteering","Helping an organization or community event demonstrates service, initiative, dependability, and collaboration."],
  ["Personal projects","Building, repairing, creating, organizing, or learning independently can demonstrate technical skill, curiosity, and problem-solving."],
  ["Military experience","Mission focus, leadership, training, safety, logistics, and accountability can translate into clear civilian workplace skills."]
];
const phases=[
  {label:"Experience",start:0,end:3},
  {label:"Skills",start:4,end:6},
  {label:"Build Résumé",start:7,end:10},
  {label:"Interview Ready",start:11,end:12},
  {label:"District Map",start:13,end:16},
];

export default function ResumeDistrict(){
  const [journey,setJourney]=useState<Journey>(DEFAULT),[ready,setReady]=useState(false),[session,setSession]=useState<Session|null>(null),[authReady,setAuthReady]=useState(false);
  const [email,setEmail]=useState(""),[sent,setSent]=useState(false),[open,setOpen]=useState<string|null>(null),[playing,setPlaying]=useState(false),[narrationStarted,setNarrationStarted]=useState(false),[audioOn,setAudioOn]=useState(true),[sync,setSync]=useState<"local"|"saving"|"saved"|"error">("local");
  const video=useRef<HTMLVideoElement>(null); const scene=journey.scene; const numbered=String(scene+1).padStart(2,"0"); const activity=enhancements[scene];
  useEffect(()=>{ try{const saved=localStorage.getItem(STORAGE_KEY);if(saved)setJourney({...DEFAULT,...JSON.parse(saved)});}catch{} setReady(true);},[]);
  useEffect(()=>{if(ready)localStorage.setItem(STORAGE_KEY,JSON.stringify(journey));},[journey,ready]);
  useEffect(()=>{if(!supabase){setAuthReady(true);return;} supabase.auth.getSession().then(({data})=>{setSession(data.session);setAuthReady(true)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe();},[]);
  useEffect(()=>{if(!session||!supabase)return;supabase.from("module_progress").select("journey_state").eq("user_id",session.user.id).eq("module_id",MODULE_ID).maybeSingle().then(({data,error})=>{if(error)return setSync("error");if(data?.journey_state){const remote={...DEFAULT,...data.journey_state} as Journey;setJourney(local=>remote.completed.length>local.completed.length||remote.scene>local.scene?remote:local)}setSync("saved")});},[session?.user.id]);
  useEffect(()=>{if(!session||!supabase||!ready)return;setSync("saving");const id=setTimeout(async()=>{const done=journey.completed.includes("reflection");const {error}=await supabase!.from("module_progress").upsert({user_id:session.user.id,module_id:MODULE_ID,journey_state:journey,xp:journey.xp,is_complete:done,completed_at:journey.completionDate||null},{onConflict:"user_id,module_id"});if(!error&&journey.name)await supabase!.from("profiles").update({display_name:journey.name}).eq("user_id",session.user.id);setSync(error?"error":"saved")},800);return()=>clearTimeout(id);},[journey,session?.user.id,ready]);
  useEffect(()=>{video.current?.pause();setPlaying(false);setNarrationStarted(false);video.current?.load()},[scene]);
  const progress=Math.round(((scene+1)/13)*100);
  function update(p:Partial<Journey>){setJourney(j=>({...j,...p}))}
  function answer(p:Partial<Answers>){setJourney(j=>({...j,answers:{...j.answers,...p}}))}
  function complete(id:string,xp=50){setJourney(j=>({...j,xp:j.completed.includes(id)?j.xp:j.xp+xp,completed:j.completed.includes(id)?j.completed:[...j.completed,id],completionDate:id==="reflection"?(j.completionDate||new Date().toISOString()):j.completionDate}))}
  function next(){if(scene<16)update({scene:scene+1})}
  function togglePlayback(){if(!video.current||scene>=14)return;if(playing)video.current.pause();else void video.current.play()}
  function restart(){if(!window.confirm("Restart Resume District and clear this module's saved responses?"))return;setJourney({...DEFAULT,name:journey.name})}
  async function magic(){if(!supabase||!email.trim())return;const {error}=await supabase.auth.signInWithOtp({email:email.trim(),options:{emailRedirectTo:authRedirectUrl()}});if(!error)setSent(true)}
  if(!ready||!authReady)return <main className="loading">Loading Resume District…</main>;
  if(supabaseConfigured&&!session)return <main className="auth"><section><div className="brand"><b>LU</b><span>LEVEL UP<small>RESUME DISTRICT</small></span></div><p className="kicker">YOUR NEXT DISTRICT IS OPEN</p><h1>Sign in to continue</h1><p>Your Level Up account carries your Discovery progress into Resume District.</p>{sent?<div className="notice"><Check/> Check your email for the secure sign-in link.</div>:<><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} onKeyDown={e=>e.key==="Enter"&&magic()}/></label><button onClick={magic}>Email my sign-in link <ArrowRight/></button></>}</section></main>;
  if(!journey.name)return <main className="auth"><section><div className="brand"><b>LU</b><span>LEVEL UP<small>RESUME DISTRICT</small></span></div><p className="kicker">INTERVIEW UNLOCKED • EPISODE 1</p><h1>Show what you can do.</h1><p>Turn work, school, caregiving, service, and life experience into résumé-ready evidence.</p><label>What should we call you?<input autoFocus onKeyDown={e=>{if(e.key==="Enter"&&(e.target as HTMLInputElement).value.trim())update({name:(e.target as HTMLInputElement).value.trim()})}}/></label><p className="hint">Enter your name and press Enter to begin.</p></section></main>;
  return <main className="app">
    <header><div className="brand"><b>LU</b><span>LEVEL UP<small>RESUME DISTRICT</small></span></div><div className="hud"><span>{titles[scene]}</span><div><i style={{width:`${Math.min(progress,100)}%`}}/></div><small>SCENE {scene+1} OF 17</small><strong>{journey.xp} XP</strong></div><div className="hud-actions"><span className={`cloud ${sync}`} title={sync}>{sync==="error"?<CloudOff/>:<Cloud/>}</span><button className="icon" disabled={scene===0} onClick={()=>update({scene:scene-1})} aria-label="Previous scene"><ArrowLeft/></button><button className="icon" onClick={()=>setOpen("access")} aria-label="Accessibility and scene description"><Accessibility/></button><button className="icon" disabled={scene>=14} onClick={togglePlayback} aria-label={playing?"Pause narration":"Play narration"}>{playing?<Pause/>:<Play/>}</button><button className="icon" disabled={scene>=14} onClick={()=>setAudioOn(v=>!v)} aria-label={audioOn?"Mute narration":"Turn on narration"}>{audioOn?<Volume2/>:<VolumeX/>}</button><button className="icon" onClick={restart} aria-label="Restart Resume District"><RotateCcw/></button><button className="icon" onClick={()=>supabase?.auth.signOut()} aria-label="Sign out"><LogOut/></button></div></header>
    <section className="stage" aria-label={titles[scene]}>
      <img src={`assets/resume/scenes/slide-${numbered}.webp`} alt={alt(scene)}/>
      {scene<14&&<><div className={`caption-mask ${narrationStarted?"visible":""}`} aria-hidden="true"/><video ref={video} className="caption-video" src={`assets/resume/scenes/narration-${numbered}.mp4`} playsInline muted={!audioOn} preload="metadata" onPlay={()=>{setPlaying(true);setNarrationStarted(true)}} onPause={()=>setPlaying(false)} onEnded={()=>{setPlaying(false);setNarrationStarted(false)}}/></>}
      {scene<14&&!narrationStarted&&<button className="resume-narration" onClick={togglePlayback}><Play/> Play narration</button>}
      {activity&&<button className="hotspot" onClick={()=>setOpen(activity.kind)}><Sparkles/>{journey.completed.includes(activity.kind)?"Review: ":""}{activity.label}</button>}
      {scene<13&&<button className="next-world" onClick={next} aria-label="Continue to the next Resume District scene"><span>Continue journey</span></button>}
      {scene===13&&<a className="next-world map-return" href={PORTAL}><span>Return to district map</span></a>}
    </section>
    <nav className="stage-nav" aria-label="Resume District levels">{phases.map((phase,index)=>{const active=scene>=phase.start&&scene<=phase.end;const available=scene>=phase.start||index===0;const complete=scene>phase.end;return <button key={phase.label} disabled={!available} className={`${active?"active":""} ${complete?"complete":""}`} onClick={()=>update({scene:phase.start})}><span>{complete?<Check/>:index+1}</span>{phase.label}</button>})}</nav>
    {open&&<Modal title={modalTitle(open)} close={()=>setOpen(null)}>{renderActivity(open,journey,answer,complete,()=>setOpen(null))}</Modal>}
  </main>
}

function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="modal-backdrop" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&close()}><section className="modal" role="dialog" aria-modal="true" aria-label={title}><header><div><p className="kicker">RESUME DISTRICT • SKILL LAB</p><h2>{title}</h2></div><button className="icon" onClick={close} aria-label="Close"><X/></button></header>{children}</section></div>}
function Field({label,value,onChange,placeholder=""}:{label:string;value?:string;onChange:(v:string)=>void;placeholder?:string}){return <label>{label}<input value={value||""} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/></label>}
function Choices({label,items,value,onChange}:{label:string;items:string[];value?:string;onChange:(v:string)=>void}){return <fieldset><legend>{label}</legend><div className="choices">{items.map(x=><button key={x} className={value===x?"selected":""} onClick={()=>onChange(x)}>{value===x&&<Check/>}{x}</button>)}</div></fieldset>}
function renderActivity(kind:string,j:Journey,answer:(p:Partial<Answers>)=>void,complete:(id:string,xp?:number)=>void,close:()=>void){const a=j.answers;
  if(kind==="lens")return <><p>Experience does not have to be paid to demonstrate workplace value. Explore each source, then choose one for the Translator.</p><div className="flip-grid">{lens.map(([t,d])=><details key={t}><summary>{t}<small>Flip to reveal skills</small></summary><p>{d}</p></details>)}</div><button className="primary" onClick={()=>{complete("lens");close()}}>I found experience I can use</button></>;
  if(kind==="translator"){const bullet=a.bullet||buildBullet(a);return <><p>Describe only what really happened. We will help shape your words—we will not invent accomplishments or numbers.</p><Choices label="Where did this experience happen?" items={["Paid work","School","Volunteering","Caregiving","Military","Sports or club","Personal project"]} value={a.experienceType} onChange={v=>answer({experienceType:v})}/><Field label="What did you actually do?" value={a.task} onChange={v=>answer({task:v})} placeholder="Example: organized appointments and transportation"/><Choices label="Choose a strong opening action" items={["Coordinated","Organized","Supported","Created","Resolved","Maintained","Trained","Assisted"]} value={a.action} onChange={v=>answer({action:v})}/><Field label="What skill did that demonstrate?" value={a.skill} onChange={v=>answer({skill:v})} placeholder="planning, communication, teamwork…"/><Field label="What changed or was accomplished? (optional)" value={a.result} onChange={v=>answer({result:v})} placeholder="Only include a result you can support"/><div className="draft"><b>Your editable résumé bullet</b><textarea value={a.bullet??bullet} onChange={e=>answer({bullet:e.target.value})}/><small>Review every word. Remove anything that is not accurate.</small></div><button className="primary" disabled={!a.task||!a.action} onClick={()=>{answer({bullet:a.bullet||bullet});complete("translator",100);close()}}>Save my résumé bullet</button></>}
  if(kind==="anatomy")return <><p>Open each résumé section to learn its job.</p><div className="flip-grid">{[["Contact","Name, phone, professional email, and location—not a full street address."],["Summary","A short, targeted snapshot of the value you offer."],["Skills","Relevant, honest skills that also appear in the target job posting."],["Experience","Evidence of what you did, how you did it, and the value it created."],["Education","School, credentials, training, and relevant certifications."]].map(([t,d])=><details key={t}><summary>{t}<small>Explore section</small></summary><p>{d}</p></details>)}</div><button className="primary" onClick={()=>{complete("anatomy");close()}}>Résumé anatomy explored</button></>;
  if(kind==="keywords")return <Challenge prompt="A posting asks for customer service, accurate records, and teamwork. Which bullet is better tailored?" options={["Helped customers and did other tasks.","Assisted customers, maintained accurate order records, and coordinated with teammates during busy shifts."]} correct={1} explain="The second bullet uses relevant language and gives concrete evidence without copying claims the applicant cannot support." done={()=>{complete("keywords",75);close()}}/>;
  if(kind==="brand")return <Challenge prompt="Before applying, what is the strongest next step?" options={["Delete every account immediately.","Review public-facing content, privacy settings, username, and profile information.","Assume employers never search online."]} correct={1} explain="A thoughtful review protects privacy and helps ensure your public presence supports the professional story you want to tell." done={()=>{complete("brand",50);close()}}/>;
  if(kind==="integrity")return <Challenge prompt="Which résumé choice is honest and strong?" options={["Claim a manager title because you sometimes helped new coworkers.","Say nothing about helping new coworkers.","Write: Supported onboarding by demonstrating routine tasks and answering new-employee questions."]} correct={2} explain="Strengthening truthful experience is good résumé writing. Changing your title or inventing authority is not." done={()=>{complete("integrity",75);close()}}/>;
  if(kind==="builder")return <><h3>Your résumé evidence</h3><div className="draft"><b>Saved bullet</b><p>{a.bullet||"Return to the Experience Translator to create your first bullet."}</p></div><Choices label="What support would help you next?" items={["Start my first résumé","Improve my current résumé","Review keywords","Get feedback from my Career Coach","Prepare for applications"]} value={a.support} onChange={v=>answer({support:v})}/><button className="primary" onClick={()=>{complete("builder");close()}}>Save my résumé plan</button></>;
  if(kind==="reflection")return <><Choices label="Which lesson helped you level up most?" items={["My experience counts","Transferable skills","Keywords","Tailoring a résumé","Professional email","Digital presence"]} value={a.lesson} onChange={v=>answer({lesson:v})}/><Field label="What experience can you add this week?" value={a.addThisWeek} onChange={v=>answer({addThisWeek:v})}/><Choices label="What are you most likely to do next?" items={["Create my first résumé","Update my résumé","Improve my email address","Apply for jobs","Review my social media","Meet with my Career Coach"]} value={a.nextAction} onChange={v=>answer({nextAction:v})}/><Choices label="Did you create or update a résumé?" items={["Yes","Not yet"]} value={a.createdResume} onChange={v=>answer({createdResume:v})}/><button className="primary" disabled={!a.lesson||!a.addThisWeek||!a.nextAction} onClick={()=>{complete("reflection",100);close()}}>Complete Resume District</button></>;
  return <><h3>Accessibility controls</h3><p>Narration is user-controlled. Captions appear in the original narrated media. Every enhanced activity is keyboard accessible and provides visible focus and text instructions.</p><p>You can pause narration, move backward, and review activities without losing progress.</p><button className="primary" onClick={close}>Done</button></>;
}
function Challenge({prompt,options,correct,explain,done}:{prompt:string;options:string[];correct:number;explain:string;done:()=>void}){const [pick,setPick]=useState<number|null>(null);return <><h3>{prompt}</h3><div className="challenge">{options.map((x,i)=><button className={pick===i?(i===correct?"right":"wrong"):""} onClick={()=>setPick(i)} key={x}>{x}</button>)}</div>{pick!==null&&<div className="feedback"><b>{pick===correct?"Strong choice":"Look again"}</b><p>{explain}</p></div>}<button className="primary" disabled={pick!==correct} onClick={done}>Save and continue</button></>}
function buildBullet(a:Answers){if(!a.action||!a.task)return "Choose an action and describe what you did to create a draft.";return `${a.action} ${a.task.trim().replace(/[.]$/,"")}${a.skill?` using ${a.skill}`:""}${a.result?` to ${a.result}`:""}.`}
function modalTitle(k:string){return ({lens:"Experience Counts",translator:"Experience Translator",anatomy:"Résumé Anatomy",keywords:"Keyword Forge",brand:"Digital Presence Check",integrity:"Integrity Crossroads",builder:"Résumé Readiness",reflection:"Resume District Reflection",access:"Accessibility"} as Record<string,string>)[k]||"Resume District"}
function alt(i:number){return ["A learner enters a neon city where Resume District is the first destination.","A neon Level Up district map showing Resume District leading toward Interview Arena.","A learner recognizes school, caregiving, volunteering, and projects as sources of transferable skills.","A glowing transferable-skills card unlocks among teamwork, communication, reliability, leadership, and problem-solving symbols.","A path opens from Resume District toward Interview Arena.","A résumé path comparison shows ATS-friendly choices and dead ends.","A recruiter reviews résumés and sorts strong evidence from unclear claims.","A learner uses the Keyword Forge to align truthful experience with a job posting.","A learner protects a professional digital identity from risky public content.","A learner chooses the honest path toward lasting success.","A guided résumé builder organizes summary, skills, experience, and education.","The Interview Gate opens after résumé readiness achievements.","The Level Up map displays a reflection checkpoint after Resume District.","Resume District learning summary.","Interview Arena preview.","First Day Challenge preview.","Money Moves preview."][i]}
